name: 'cross-gem'
description: 'Cross compiles a native Ruby gem written in Rust'
author: 'oxidize-rs'
branding:
  icon: 'chevron-right'
  color: 'gray-dark'
inputs:
  platform:
    required: true
    description: 'The target Ruby platform'
  directory:
    description: 'Directory of gem to build'
  command:
    description: 'Command to build gem inside of container'
  setup:
    description: 'Extra setup script to run inside container'
  version:
    description: 'Docker version tag for container (corresponds to rb-sys version)'
  env:
    description: 'Extra env vars to set when compiling'
runs:
  using: 'node16'
  main: 'dist/index.js'
