name: 'cross-gem'
description: 'Cross compiles a native Ruby gem written in Rust'
author: 'oxidize-rs'
inputs:
  platform: 
    required: true
    description: 'The target Ruby platform'
  directory: # change this
    description: 'Directory of gem to build'
runs:
  using: 'node16'
  main: 'dist/index.js'
